# Generated by Django 3.2.5 on 2022-02-12 06:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullDetailEmployer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='uploads/category')),
                ('coverPic', models.ImageField(blank=True, null=True, upload_to='uploads/category')),
                ('employerName', models.CharField(max_length=121)),
                ('Email', models.CharField(max_length=121)),
                ('phoneNumber', models.CharField(max_length=121)),
                ('website', models.CharField(max_length=121)),
                ('foundedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('compnaySize', models.CharField(max_length=121)),
                ('category', models.CharField(choices=[('1', 'developer'), ('2', 'technology'), ('3', 'accounting'), ('4', 'medical'), ('5', 'government')], default=1, max_length=10)),
                ('indroductionVideoUrl', models.CharField(max_length=121)),
                ('aboutCompany', models.CharField(max_length=121)),
                ('subLeadMemberName', models.CharField(max_length=121)),
                ('subLeadMemberDesination', models.CharField(max_length=121)),
                ('subLeadMemberExperience', models.CharField(max_length=121)),
                ('location', models.CharField(max_length=121)),
                ('socailNetwork', models.CharField(max_length=121)),
                ('employerData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
