# Generated by Django 2.2 on 2022-02-23 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220211_0418'),
        ('accounts', '0004_fulldetailemployer'),
    ]

    operations = [
    ]
