# Generated by Django 2.2 on 2022-02-23 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20220223_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='uploads/category')),
            ],
        ),
        migrations.CreateModel(
            name='FullDetailEmploye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImgae', models.ImageField(blank=True, null=True, upload_to='uploads/category')),
                ('fullName', models.CharField(max_length=121)),
                ('email', models.CharField(max_length=121)),
                ('phoneNumber', models.CharField(max_length=121)),
                ('age', models.CharField(max_length=121)),
                ('gender', models.CharField(max_length=121)),
                ('qualification', models.CharField(max_length=121)),
                ('language', models.CharField(max_length=121)),
                ('jobTitle', models.CharField(max_length=121)),
                ('experienceTime', models.CharField(max_length=121)),
                ('salaryType', models.CharField(max_length=121)),
                ('categories', models.CharField(max_length=121)),
                ('socialNetwork', models.CharField(max_length=121)),
                ('location', models.CharField(max_length=121)),
                ('address', models.CharField(max_length=121)),
                ('employeeData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
