# Generated by Django 2.2 on 2022-02-23 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_fulldetailemploye_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fulldetailemploye',
            old_name='socialNetwork',
            new_name='portfolioLink',
        ),
    ]
