# Generated by Django 2.2 on 2022-03-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_fulldetailemploye_socialnetwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='PortfolioUrl',
            field=models.CharField(default='shios', max_length=121),
        ),
    ]
