# Generated by Django 2.2 on 2022-03-03 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220303_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumeshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume1', models.FileField(upload_to='uploads/category')),
                ('PortfolioUrl1', models.CharField(default='shios', max_length=121)),
                ('Data1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
