# Generated by Django 2.2 on 2022-03-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulldetailemployer',
            name='foundedDate',
        ),
    ]
