# Generated by Django 2.2 on 2022-04-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_fulldetailemployer_foundeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='phone',
            field=models.CharField(default='123', max_length=121),
        ),
    ]
