# Generated by Django 3.0.14 on 2022-04-30 12:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0015_newsletter_phone'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('blogName', models.CharField(max_length=121)),
                ('shortDesc', models.CharField(max_length=121)),
                ('longDesc', models.CharField(max_length=121)),
                ('status', models.CharField(max_length=121)),
                ('blogUesrName', models.CharField(max_length=232)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/category')),
            ],
        ),
        migrations.CreateModel(
            name='BlogMain1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField()),
                ('blogName1', models.CharField(max_length=121)),
                ('shortDesc1', models.CharField(max_length=121)),
                ('longDesc1', models.CharField(max_length=121)),
                ('status1', models.CharField(max_length=121)),
                ('blogUesrName1', models.CharField(max_length=232)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/category')),
            ],
        ),
        migrations.CreateModel(
            name='BlogShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date2', models.DateField()),
                ('blogName2', models.CharField(max_length=121)),
                ('shortDesc2', models.CharField(max_length=121)),
                ('longDesc2', models.CharField(max_length=121)),
                ('status2', models.CharField(max_length=121)),
                ('blogUesrName2', models.CharField(max_length=232)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='uploads/category')),
            ],
        ),
        migrations.CreateModel(
            name='BlogShow1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date21', models.DateField()),
                ('blogName21', models.CharField(max_length=121)),
                ('shortDesc21', models.CharField(max_length=121)),
                ('longDesc21', models.CharField(max_length=121)),
                ('status21', models.CharField(max_length=121)),
                ('blogUesrName21', models.CharField(max_length=232)),
                ('image21', models.ImageField(blank=True, null=True, upload_to='uploads/category')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutMmeber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=121)),
                ('lname', models.CharField(max_length=121)),
                ('cname', models.CharField(max_length=121)),
                ('streed', models.CharField(max_length=121)),
                ('city', models.CharField(max_length=121)),
                ('state', models.CharField(max_length=121)),
                ('pin', models.CharField(max_length=121)),
                ('phone', models.CharField(max_length=121)),
                ('email', models.CharField(max_length=121)),
                ('paymentDone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MainBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogdate', models.DateField()),
                ('name', models.CharField(max_length=1211)),
                ('desc1short', models.CharField(max_length=1211)),
                ('decs2long', models.CharField(max_length=1121)),
                ('blogStatus', models.CharField(max_length=1211)),
                ('usernameBlog', models.CharField(max_length=2312)),
                ('imageBlog', models.ImageField(blank=True, null=True, upload_to='uploads/category')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAdminn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=232)),
                ('password', models.CharField(max_length=121)),
            ],
        ),
        migrations.CreateModel(
            name='TrainCertPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/category')),
                ('Category', models.CharField(choices=[('1', 'Training'), ('2', 'Training&Certification'), ('3', 'Placement'), ('4', 'Traingin&Placement&Certification')], default=1, max_length=10)),
                ('title', models.CharField(max_length=121)),
                ('price', models.CharField(max_length=121)),
                ('disc', models.CharField(max_length=121)),
                ('feature1', models.CharField(max_length=121)),
                ('featured2', models.CharField(max_length=121)),
                ('featured3', models.CharField(max_length=121)),
                ('featured4', models.CharField(max_length=121)),
                ('featured5', models.CharField(max_length=121)),
                ('featured6', models.CharField(max_length=121)),
                ('skill', models.CharField(max_length=12121)),
                ('benifits', models.CharField(max_length=121)),
                ('Technology', models.CharField(max_length=121)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship'), ('4', 'Remotely')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('last_date', models.DateTimeField()),
                ('company_name', models.CharField(max_length=100)),
                ('company_description', models.CharField(max_length=300)),
                ('website', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('filled', models.BooleanField(default=False)),
                ('salary', models.CharField(default='', max_length=100)),
                ('opening', models.CharField(default=1, max_length=121)),
                ('maincategory', models.CharField(choices=[('1', 'developer'), ('2', 'technology'), ('3', 'accounting'), ('4', 'medical'), ('5', 'government')], default=1, max_length=10)),
                ('experence', models.CharField(default='0-1 Year', max_length=122)),
                ('phoneNumber', models.CharField(default='none', max_length=102)),
                ('tags', models.ManyToManyField(to='tags.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('soft_deleted', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='jobsapp.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='jobsapp.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('user', 'job')},
            },
        ),
    ]
