# Generated by Django 3.0.14 on 2022-05-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0002_auto_20220516_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoucmentEmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyIdCard', models.FileField(blank=True, null=True, upload_to='uploads/category')),
                ('shopStablished', models.FileField(blank=True, null=True, upload_to='uploads/category')),
                ('udyogAAdhar', models.FileField(blank=True, null=True, upload_to='uploads/category')),
                ('certificateOfIncorpation', models.FileField(blank=True, null=True, upload_to='uploads/category')),
                ('msmacertificate', models.FileField(blank=True, null=True, upload_to='uploads/category')),
                ('Tan', models.FileField(blank=True, null=True, upload_to='uploads/category')),
                ('Din', models.FileField(blank=True, null=True, upload_to='uploads/category')),
            ],
        ),
    ]
