# Generated by Django 3.0.14 on 2022-05-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0003_doucmentemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='doucmentemp',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
