# Generated by Django 3.0.14 on 2022-05-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0005_auto_20220527_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='primum',
            field=models.BooleanField(default=False),
        ),
    ]
